// Code generated by goctl. DO NOT EDIT!
// Source: apply.proto

package server

import (
	"context"

	"go-zero-share/apply/rpc/internal/logic"
	"go-zero-share/apply/rpc/internal/svc"
	"go-zero-share/apply/rpc/types/apply"
)

type ApplyServer struct {
	svcCtx *svc.ServiceContext
	apply.UnimplementedApplyServer
}

func NewApplyServer(svcCtx *svc.ServiceContext) *ApplyServer {
	return &ApplyServer{
		svcCtx: svcCtx,
	}
}

func (s *ApplyServer) CreateIdentify(ctx context.Context, in *apply.CreateIdentifyReq) (*apply.CreateIdentifyReply, error) {
	l := logic.NewCreateIdentifyLogic(ctx, s.svcCtx)
	return l.CreateIdentify(in)
}

func (s *ApplyServer) CheckIdentify(ctx context.Context, in *apply.CheckIdentifyReq) (*apply.CheckIdentifyReply, error) {
	l := logic.NewCheckIdentifyLogic(ctx, s.svcCtx)
	return l.CheckIdentify(in)
}
