help.api: # {服务名称}.rpc或者 {服务名称}.api
  build:
    dockerfile: service/help/api/Dockerfile # service/{服务名称}/{rpc|api}/Dockerfile
  environment:
    - TZ=Asia/Shanghai
  privileged: true
  ports:
    - "8892:8892"  # rpc或者api服务的自己的端口
  stdin_open: true
  tty: true
  networks:
    - backend
  restart: always

help.rpc: # {服务名称}.rpc或者 {服务名称}.api
  build:
    dockerfile: service/help/rpc/Dockerfile # service/{服务名称}/{rpc|api}/Dockerfile
  environment:
    - TZ=Asia/Shanghai
  privileged: true
  ports:
    - "8884:8884"  # rpc或者api服务的自己的端口
  stdin_open: true
  tty: true
  networks:
    - backend
  restart: always