// Code generated by goctl. DO NOT EDIT.
package types

type ReqsReq struct {
	Start int64 `json:"start"`
	End   int64 `json:"end"`
	Order int64 `json:"order"`
}

type ReqsReply struct {
	ReqList     []Request `json:"requests"`
	RequestsNum int64     `json:"requests_num"`
}

type ReqSearchReq struct {
	Start         int64  `json:"start"`
	End           int64  `json:"end"`
	SearchContent string `json:"search_content"`
}

type ReqSearchReply struct {
	ReqList     []Search `json:"requests"`
	RequestsNum int64    `json:"requests_num"`
}

type BeforeHelpReq struct {
	RequestId int64 `json:"request_id"`
}

type BeforeHelpReply struct {
	Status int64 `json:"status"`
}

type UserInfoReq struct {
}

type UserInfoReply struct {
	Request int64 `json:"request"`
	Help    int64 `json:"help"`
	Wealth  int64 `json:"wealth"`
}

type AddRequestsReq struct {
	UserId   int64    `json:"user_id"`
	Title    string   `json:"title"`
	Author   []string `json:"author"`
	Magazine string   `json:"magazine"`
	Link     string   `json:"link"`
	Content  string   `json:"content"`
	Wealth   int64    `json:"wealth"`
}

type AddRequestsReply struct {
	Code int64 `json:"code"`
}

type Request struct {
	Id             int64  `json:"request_id"`
	Title          string `json:"title"`
	Author         string `json:"author"`
	Magazine       string `json:"magazine"`
	Link           string `json:"link"`
	RequestTime    string `json:"request_time"`
	RequestContent string `json:"request_content"`
	Wealth         int64  `json:"wealth"`
}

type Search struct {
	HelpId         int64  `json:"help_id"`
	RequestId      int64  `json:"request_id"`
	RequestTime    string `json:"request_time"`
	RequestContent string `json:"request_content"`
	Wealth         int64  `json:"wealth"`
	RequestStatus  int64  `json:"request_status"`
}
