// Code generated by goctl. DO NOT EDIT.
package types

type ReqsReq struct {
	Start int64 `json:"start"`
	End   int64 `json:"end"`
	Order int64 `json:"order"`
}

type ReqsReply struct {
	ReqList     []Request `json:"requests"`
	RequestsNum int64     `json:"requests_num"`
}

type ReqSearchReq struct {
	Start         int64  `json:"start"`
	End           int64  `json:"end"`
	SearchContent string `json:"search_content"`
}

type ReqSearchReply struct {
	ReqList     []Search `json:"requests"`
	RequestsNum int64    `json:"requests_num"`
}

type BeforeHelpReq struct {
	RequestId int64 `json:"request_id"`
}

type BeforeHelpReply struct {
	Status int64 `json:"status"`
}

type UserInfoReq struct {
}

type UserInfoReply struct {
	Request int64 `json:"request"`
	Help    int64 `json:"help"`
	Wealth  int64 `json:"wealth"`
}

type UserReqReq struct {
	Start int64 `json:"start"`
	End   int64 `json:"end"`
	Type  int64 `json:"type"`
}

type UserReqReply struct {
	Requests   []UserReq `json:"requests"`
	RequestNum int64     `json:"request_num"`
}

type AddRequestsReq struct {
	Title    string   `json:"title"`
	Author   []string `json:"author"`
	Magazine string   `json:"magazine"`
	Link     string   `json:"link"`
	Content  string   `json:"content"`
	Wealth   int64    `json:"wealth"`
}

type AddRequestsReply struct {
}

type UserHelpReq struct {
	Start int64 `json:"start"`
	End   int64 `json:"end"`
	Type  int64 `json:"type"`
}

type UserHelpReply struct {
	Requests []UserReq `json:"requests"`
	HelpNum  int64     `json:"help_num"`
}

type DownloadReq struct {
	RequestId int64 `json:"request_id"`
}

type DownloadReply struct {
	Url string `json:"url"`
}

type ConfirmedReq struct {
	RequestId int64 `json:"request_id"`
}

type ComplaintReq struct {
	RequestId int64  `json:"request_id"`
	Content   string `json:"content"`
}

type Request struct {
	Id             int64  `json:"request_id"`
	Title          string `json:"title"`
	Author         string `json:"author"`
	Magazine       string `json:"magazine"`
	Link           string `json:"link"`
	RequestTime    string `json:"request_time"`
	RequestContent string `json:"request_content"`
	Wealth         int64  `json:"wealth"`
}

type Search struct {
	HelpId         int64  `json:"help_id"`
	ReqTitle       string `json:"request_title"`
	RequestId      int64  `json:"request_id"`
	RequestTime    string `json:"request_time"`
	RequestContent string `json:"request_content"`
	Wealth         int64  `json:"wealth"`
	RequestStatus  int64  `json:"request_status"`
}

type UserReq struct {
	Type           int64  `json:"type"`
	HelpId         int64  `json:"help_id"`
	ReqTitle       string `json:"request_title"`
	RequestId      int64  `json:"request_id"`
	RequestTime    string `json:"request_time"`
	RequestContent string `json:"request_content"`
	Wealth         int64  `json:"wealth"`
}
