// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"soft2_backend/service/message/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/message/get-all-messages",
				Handler: GetMessageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/message/read",
				Handler: ReadMessageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/message/delete",
				Handler: DeleteMessageHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
