// Code generated by goctl. DO NOT EDIT!
// Source: help.proto

package server

import (
	"context"

	"soft2_backend/service/help/rpc/internal/logic"
	"soft2_backend/service/help/rpc/internal/svc"
	"soft2_backend/service/help/rpc/types/help"
)

type HelpServer struct {
	svcCtx *svc.ServiceContext
	help.UnimplementedHelpServer
}

func NewHelpServer(svcCtx *svc.ServiceContext) *HelpServer {
	return &HelpServer{
		svcCtx: svcCtx,
	}
}

func (s *HelpServer) RegisterUser(ctx context.Context, in *help.IdReq) (*help.Reply, error) {
	l := logic.NewRegisterUserLogic(ctx, s.svcCtx)
	return l.RegisterUser(in)
}

func (s *HelpServer) UpDateStatus(ctx context.Context, in *help.UpdateReq) (*help.Reply, error) {
	l := logic.NewUpDateStatusLogic(ctx, s.svcCtx)
	return l.UpDateStatus(in)
}

func (s *HelpServer) GetUserWealth(ctx context.Context, in *help.WealthReq) (*help.WealthReply, error) {
	l := logic.NewGetUserWealthLogic(ctx, s.svcCtx)
	return l.GetUserWealth(in)
}
