// Code generated by goctl. DO NOT EDIT.
// Source: paper.proto

package server

import (
	"context"
	"soft2_backend/service/paper/rpc/internal/logic"
	"soft2_backend/service/paper/rpc/internal/svc"
	paper2 "soft2_backend/service/paper/rpc/types/paper"
)

type StreamGreeterServer struct {
	svcCtx *svc.ServiceContext
	paper2.UnimplementedStreamGreeterServer
}

func NewStreamGreeterServer(svcCtx *svc.ServiceContext) *StreamGreeterServer {
	return &StreamGreeterServer{
		svcCtx: svcCtx,
	}
}

func (s *StreamGreeterServer) CheckScholar(ctx context.Context, in *paper2.CheckScholarReq) (*paper2.CreateScholarReply, error) {
	l := logic.NewCheckScholarLogic(ctx, s.svcCtx)
	return l.CheckScholar(in)
}
