// Code generated by goctl. DO NOT EDIT.
// Source: paper.proto

package server

import (
	"context"

	"soft2_backend/service/paper/rpc/internal/logic"
	"soft2_backend/service/paper/rpc/internal/svc"
	"soft2_backend/service/paper/rpc/types/paper"
)

type StreamGreeterServer struct {
	svcCtx *svc.ServiceContext
	paper.UnimplementedStreamGreeterServer
}

func NewStreamGreeterServer(svcCtx *svc.ServiceContext) *StreamGreeterServer {
	return &StreamGreeterServer{
		svcCtx: svcCtx,
	}
}

func (s *StreamGreeterServer) CheckScholar(ctx context.Context, in *paper.CheckScholarReq) (*paper.CreateScholarReply, error) {
	l := logic.NewCheckScholarLogic(ctx, s.svcCtx)
	return l.CheckScholar(in)
}

func (s *StreamGreeterServer) ListCheckScholar(ctx context.Context, in *paper.ListCheckScholarReq) (*paper.ListCreateScholarReply, error) {
	l := logic.NewListCheckScholarLogic(ctx, s.svcCtx)
	return l.ListCheckScholar(in)
}

func (s *StreamGreeterServer) MovePaper(ctx context.Context, in *paper.MovePaperReq) (*paper.MovePaperReply, error) {
	l := logic.NewMovePaperLogic(ctx, s.svcCtx)
	return l.MovePaper(in)
}

func (s *StreamGreeterServer) GetPaperName(ctx context.Context, in *paper.GetPaperNameReq) (*paper.GetPaperNameReply, error) {
	l := logic.NewGetPaperNameLogic(ctx, s.svcCtx)
	return l.GetPaperName(in)
}
