// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: paper.proto

package paper

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckScholarReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScholarId string `protobuf:"bytes,1,opt,name=scholarId,proto3" json:"scholarId,omitempty"`
}

func (x *CheckScholarReq) Reset() {
	*x = CheckScholarReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckScholarReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckScholarReq) ProtoMessage() {}

func (x *CheckScholarReq) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckScholarReq.ProtoReflect.Descriptor instead.
func (*CheckScholarReq) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{0}
}

func (x *CheckScholarReq) GetScholarId() string {
	if x != nil {
		return x.ScholarId
	}
	return ""
}

type CreateScholarReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScholarName string `protobuf:"bytes,1,opt,name=scholarName,proto3" json:"scholarName,omitempty"`
	Org         string `protobuf:"bytes,2,opt,name=org,proto3" json:"org,omitempty"`
	PaperNum    int64  `protobuf:"varint,3,opt,name=paperNum,proto3" json:"paperNum,omitempty"`
	Url         string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *CreateScholarReply) Reset() {
	*x = CreateScholarReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paper_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateScholarReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScholarReply) ProtoMessage() {}

func (x *CreateScholarReply) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScholarReply.ProtoReflect.Descriptor instead.
func (*CreateScholarReply) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{1}
}

func (x *CreateScholarReply) GetScholarName() string {
	if x != nil {
		return x.ScholarName
	}
	return ""
}

func (x *CreateScholarReply) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *CreateScholarReply) GetPaperNum() int64 {
	if x != nil {
		return x.PaperNum
	}
	return 0
}

func (x *CreateScholarReply) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ListCheckScholarReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScholarId []string `protobuf:"bytes,1,rep,name=scholarId,proto3" json:"scholarId,omitempty"`
}

func (x *ListCheckScholarReq) Reset() {
	*x = ListCheckScholarReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paper_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCheckScholarReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCheckScholarReq) ProtoMessage() {}

func (x *ListCheckScholarReq) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCheckScholarReq.ProtoReflect.Descriptor instead.
func (*ListCheckScholarReq) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{2}
}

func (x *ListCheckScholarReq) GetScholarId() []string {
	if x != nil {
		return x.ScholarId
	}
	return nil
}

type ListCreateScholarReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scholars []*CreateScholarReply `protobuf:"bytes,1,rep,name=scholars,proto3" json:"scholars,omitempty"`
}

func (x *ListCreateScholarReply) Reset() {
	*x = ListCreateScholarReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paper_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCreateScholarReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCreateScholarReply) ProtoMessage() {}

func (x *ListCreateScholarReply) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCreateScholarReply.ProtoReflect.Descriptor instead.
func (*ListCreateScholarReply) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{3}
}

func (x *ListCreateScholarReply) GetScholars() []*CreateScholarReply {
	if x != nil {
		return x.Scholars
	}
	return nil
}

type MovePaperReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PaperId  string `protobuf:"bytes,1,opt,name=paperId,proto3" json:"paperId,omitempty"`
	OwnerId  string `protobuf:"bytes,2,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	TargetId string `protobuf:"bytes,3,opt,name=targetId,proto3" json:"targetId,omitempty"`
}

func (x *MovePaperReq) Reset() {
	*x = MovePaperReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paper_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovePaperReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovePaperReq) ProtoMessage() {}

func (x *MovePaperReq) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovePaperReq.ProtoReflect.Descriptor instead.
func (*MovePaperReq) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{4}
}

func (x *MovePaperReq) GetPaperId() string {
	if x != nil {
		return x.PaperId
	}
	return ""
}

func (x *MovePaperReq) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *MovePaperReq) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type MovePaperReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *MovePaperReply) Reset() {
	*x = MovePaperReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paper_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovePaperReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovePaperReply) ProtoMessage() {}

func (x *MovePaperReply) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovePaperReply.ProtoReflect.Descriptor instead.
func (*MovePaperReply) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{5}
}

func (x *MovePaperReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

type GetPaperReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PaperId string `protobuf:"bytes,1,opt,name=paperId,proto3" json:"paperId,omitempty"`
}

func (x *GetPaperReq) Reset() {
	*x = GetPaperReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paper_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPaperReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaperReq) ProtoMessage() {}

func (x *GetPaperReq) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaperReq.ProtoReflect.Descriptor instead.
func (*GetPaperReq) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{6}
}

func (x *GetPaperReq) GetPaperId() string {
	if x != nil {
		return x.PaperId
	}
	return ""
}

type GetPaperReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PaperName string        `protobuf:"bytes,1,opt,name=paperName,proto3" json:"paperName,omitempty"`
	Authors   []*AuthorJSON `protobuf:"bytes,2,rep,name=authors,proto3" json:"authors,omitempty"`
	Org       string        `protobuf:"bytes,3,opt,name=org,proto3" json:"org,omitempty"`
	Year      int64         `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
}

func (x *GetPaperReply) Reset() {
	*x = GetPaperReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paper_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPaperReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaperReply) ProtoMessage() {}

func (x *GetPaperReply) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaperReply.ProtoReflect.Descriptor instead.
func (*GetPaperReply) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{7}
}

func (x *GetPaperReply) GetPaperName() string {
	if x != nil {
		return x.PaperName
	}
	return ""
}

func (x *GetPaperReply) GetAuthors() []*AuthorJSON {
	if x != nil {
		return x.Authors
	}
	return nil
}

func (x *GetPaperReply) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *GetPaperReply) GetYear() int64 {
	if x != nil {
		return x.Year
	}
	return 0
}

type ListGetPaperReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PaperId []string `protobuf:"bytes,1,rep,name=paperId,proto3" json:"paperId,omitempty"`
}

func (x *ListGetPaperReq) Reset() {
	*x = ListGetPaperReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paper_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGetPaperReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGetPaperReq) ProtoMessage() {}

func (x *ListGetPaperReq) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGetPaperReq.ProtoReflect.Descriptor instead.
func (*ListGetPaperReq) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{8}
}

func (x *ListGetPaperReq) GetPaperId() []string {
	if x != nil {
		return x.PaperId
	}
	return nil
}

type ListGetPaperReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Papers []*GetPaperReply `protobuf:"bytes,1,rep,name=papers,proto3" json:"papers,omitempty"`
}

func (x *ListGetPaperReply) Reset() {
	*x = ListGetPaperReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paper_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGetPaperReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGetPaperReply) ProtoMessage() {}

func (x *ListGetPaperReply) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGetPaperReply.ProtoReflect.Descriptor instead.
func (*ListGetPaperReply) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{9}
}

func (x *ListGetPaperReply) GetPapers() []*GetPaperReply {
	if x != nil {
		return x.Papers
	}
	return nil
}

type AuthorJSON struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id    string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	HasId bool   `protobuf:"varint,3,opt,name=hasId,proto3" json:"hasId,omitempty"`
}

func (x *AuthorJSON) Reset() {
	*x = AuthorJSON{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paper_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorJSON) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorJSON) ProtoMessage() {}

func (x *AuthorJSON) ProtoReflect() protoreflect.Message {
	mi := &file_paper_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorJSON.ProtoReflect.Descriptor instead.
func (*AuthorJSON) Descriptor() ([]byte, []int) {
	return file_paper_proto_rawDescGZIP(), []int{10}
}

func (x *AuthorJSON) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AuthorJSON) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuthorJSON) GetHasId() bool {
	if x != nil {
		return x.HasId
	}
	return false
}

var File_paper_proto protoreflect.FileDescriptor

var file_paper_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x61, 0x70, 0x65, 0x72, 0x22, 0x2f, 0x0a, 0x0f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x63, 0x68,
	0x6f, 0x6c, 0x61, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x63, 0x68, 0x6f, 0x6c,
	0x61, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x63, 0x68, 0x6f,
	0x6c, 0x61, 0x72, 0x49, 0x64, 0x22, 0x76, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53,
	0x63, 0x68, 0x6f, 0x6c, 0x61, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x73,
	0x63, 0x68, 0x6f, 0x6c, 0x61, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x73, 0x63, 0x68, 0x6f, 0x6c, 0x61, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6f, 0x72, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x72, 0x67, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x70, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x70, 0x61, 0x70, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x33, 0x0a,
	0x13, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x63, 0x68, 0x6f, 0x6c, 0x61,
	0x72, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x63, 0x68, 0x6f, 0x6c, 0x61, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x73, 0x63, 0x68, 0x6f, 0x6c, 0x61, 0x72,
	0x49, 0x64, 0x22, 0x4f, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x63, 0x68, 0x6f, 0x6c, 0x61, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x35, 0x0a, 0x08,
	0x73, 0x63, 0x68, 0x6f, 0x6c, 0x61, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x63, 0x68,
	0x6f, 0x6c, 0x61, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x08, 0x73, 0x63, 0x68, 0x6f, 0x6c,
	0x61, 0x72, 0x73, 0x22, 0x5e, 0x0a, 0x0c, 0x4d, 0x6f, 0x76, 0x65, 0x50, 0x61, 0x70, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x70, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x70, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x49, 0x64, 0x22, 0x24, 0x0a, 0x0e, 0x4d, 0x6f, 0x76, 0x65, 0x50, 0x61, 0x70, 0x65, 0x72,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x27, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x50, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x70, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x70, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x80, 0x01, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x50, 0x61, 0x70, 0x65, 0x72, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x70, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x70, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x4a, 0x53, 0x4f, 0x4e, 0x52, 0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x6f, 0x72, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x72,
	0x67, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x79, 0x65, 0x61, 0x72, 0x22, 0x2b, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x65, 0x74,
	0x50, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x70, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x70, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x41, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x65, 0x74, 0x50, 0x61, 0x70,
	0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2c, 0x0a, 0x06, 0x70, 0x61, 0x70, 0x65, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x50, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x06, 0x70,
	0x61, 0x70, 0x65, 0x72, 0x73, 0x22, 0x46, 0x0a, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x4a,
	0x53, 0x4f, 0x4e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x61, 0x73, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x68, 0x61, 0x73, 0x49, 0x64, 0x32, 0xd2, 0x02,
	0x0a, 0x0d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12,
	0x41, 0x0a, 0x0c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x63, 0x68, 0x6f, 0x6c, 0x61, 0x72, 0x12,
	0x16, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x63, 0x68,
	0x6f, 0x6c, 0x61, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x63, 0x68, 0x6f, 0x6c, 0x61, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x4d, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53,
	0x63, 0x68, 0x6f, 0x6c, 0x61, 0x72, 0x12, 0x1a, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x63, 0x68, 0x6f, 0x6c, 0x61, 0x72, 0x52,
	0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x63, 0x68, 0x6f, 0x6c, 0x61, 0x72, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x37, 0x0a, 0x09, 0x4d, 0x6f, 0x76, 0x65, 0x50, 0x61, 0x70, 0x65, 0x72, 0x12, 0x13,
	0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x50, 0x61, 0x70, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x4d, 0x6f, 0x76, 0x65,
	0x50, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x34, 0x0a, 0x08, 0x47, 0x65,
	0x74, 0x50, 0x61, 0x70, 0x65, 0x72, 0x12, 0x12, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x47,
	0x65, 0x74, 0x50, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x61, 0x70,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x40, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x65, 0x74, 0x50, 0x61, 0x70, 0x65, 0x72,
	0x12, 0x16, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x65, 0x74,
	0x50, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x65, 0x74, 0x50, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x61, 0x70, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_paper_proto_rawDescOnce sync.Once
	file_paper_proto_rawDescData = file_paper_proto_rawDesc
)

func file_paper_proto_rawDescGZIP() []byte {
	file_paper_proto_rawDescOnce.Do(func() {
		file_paper_proto_rawDescData = protoimpl.X.CompressGZIP(file_paper_proto_rawDescData)
	})
	return file_paper_proto_rawDescData
}

var file_paper_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_paper_proto_goTypes = []interface{}{
	(*CheckScholarReq)(nil),        // 0: paper.CheckScholarReq
	(*CreateScholarReply)(nil),     // 1: paper.CreateScholarReply
	(*ListCheckScholarReq)(nil),    // 2: paper.ListCheckScholarReq
	(*ListCreateScholarReply)(nil), // 3: paper.ListCreateScholarReply
	(*MovePaperReq)(nil),           // 4: paper.MovePaperReq
	(*MovePaperReply)(nil),         // 5: paper.MovePaperReply
	(*GetPaperReq)(nil),            // 6: paper.GetPaperReq
	(*GetPaperReply)(nil),          // 7: paper.GetPaperReply
	(*ListGetPaperReq)(nil),        // 8: paper.ListGetPaperReq
	(*ListGetPaperReply)(nil),      // 9: paper.ListGetPaperReply
	(*AuthorJSON)(nil),             // 10: paper.AuthorJSON
}
var file_paper_proto_depIdxs = []int32{
	1,  // 0: paper.ListCreateScholarReply.scholars:type_name -> paper.CreateScholarReply
	10, // 1: paper.GetPaperReply.authors:type_name -> paper.AuthorJSON
	7,  // 2: paper.ListGetPaperReply.papers:type_name -> paper.GetPaperReply
	0,  // 3: paper.StreamGreeter.CheckScholar:input_type -> paper.CheckScholarReq
	2,  // 4: paper.StreamGreeter.ListCheckScholar:input_type -> paper.ListCheckScholarReq
	4,  // 5: paper.StreamGreeter.MovePaper:input_type -> paper.MovePaperReq
	6,  // 6: paper.StreamGreeter.GetPaper:input_type -> paper.GetPaperReq
	8,  // 7: paper.StreamGreeter.ListGetPaper:input_type -> paper.ListGetPaperReq
	1,  // 8: paper.StreamGreeter.CheckScholar:output_type -> paper.CreateScholarReply
	3,  // 9: paper.StreamGreeter.ListCheckScholar:output_type -> paper.ListCreateScholarReply
	5,  // 10: paper.StreamGreeter.MovePaper:output_type -> paper.MovePaperReply
	7,  // 11: paper.StreamGreeter.GetPaper:output_type -> paper.GetPaperReply
	9,  // 12: paper.StreamGreeter.ListGetPaper:output_type -> paper.ListGetPaperReply
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_paper_proto_init() }
func file_paper_proto_init() {
	if File_paper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_paper_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckScholarReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paper_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateScholarReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paper_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCheckScholarReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paper_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCreateScholarReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paper_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovePaperReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paper_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovePaperReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paper_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPaperReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paper_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPaperReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paper_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGetPaperReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paper_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGetPaperReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paper_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorJSON); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_paper_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paper_proto_goTypes,
		DependencyIndexes: file_paper_proto_depIdxs,
		MessageInfos:      file_paper_proto_msgTypes,
	}.Build()
	File_paper_proto = out.File
	file_paper_proto_rawDesc = nil
	file_paper_proto_goTypes = nil
	file_paper_proto_depIdxs = nil
}
