# 用于直接将pod暴露出来的Service配置文件
apiVersion: v1
kind: Service
metadata:
  name: paper
spec:
  type: NodePort # NodePort类型可以直接建立端口映射，外部cilent可以从集群中任何一个ip访问nodePort所配置的端口来访问服务
  ports:
    - Port: 8888
      nodePort: 30005
  selector:
    service: paper
---
# 将api服务和rpc服务配置在同一个pod中，因为两者高度相关
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paper
spec:
  selector:
    matchLabels:
      service: paper
  replicas: 1
  template:
    metadata:
      labels:
        service: paper
    spec:
      containers:
        - name: paper-api
          image: paper-api
          imagePullPolicy: Never # 如果image为本地构建则需要该参数
          ports:
          - containerPort: 8888
        - name: paper-rpc
          image: paper-rpc
          imagePullPolicy: Never
          ports:
          - containerPort: 8080