// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	collectFieldNames          = builder.RawFieldNames(&Collect{})
	collectRows                = strings.Join(collectFieldNames, ",")
	collectRowsExpectAutoSet   = strings.Join(stringx.Remove(collectFieldNames, "`collect_id`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`"), ",")
	collectRowsWithPlaceHolder = strings.Join(stringx.Remove(collectFieldNames, "`collect_id`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`"), "=?,") + "=?"
)

type (
	collectModel interface {
		Insert(ctx context.Context, data *Collect) (sql.Result, error)
		FindOne(ctx context.Context, collectId int64) (*Collect, error)
		FindOneByTwo(ctx context.Context, userId int64, paperId string) (*Collect, error)
		FindByUserId(ctx context.Context, userId int64) ([]Collect, error)
		Update(ctx context.Context, data *Collect) error
		Delete(ctx context.Context, collectId int64) error
	}

	defaultCollectModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Collect struct {
		CollectId  int64     `db:"collect_id"`
		UserId     int64     `db:"user_id"`
		PaperId    string    `db:"paper_id"`
		CreateTime time.Time `db:"create_time"`
	}
)

func newCollectModel(conn sqlx.SqlConn) *defaultCollectModel {
	return &defaultCollectModel{
		conn:  conn,
		table: "`collect`",
	}
}

func (m *defaultCollectModel) Delete(ctx context.Context, collectId int64) error {
	query := fmt.Sprintf("delete from %s where `collect_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, collectId)
	return err
}

func (m *defaultCollectModel) FindOne(ctx context.Context, collectId int64) (*Collect, error) {
	query := fmt.Sprintf("select %s from %s where `collect_id` = ? limit 1", collectRows, m.table)
	var resp Collect
	err := m.conn.QueryRowCtx(ctx, &resp, query, collectId)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCollectModel) FindOneByTwo(ctx context.Context, userId int64, paperId string) (*Collect, error) {
	var resp Collect
	var query string
	query = fmt.Sprintf("select %s from %s where `user_id` = ? and `paper_id` = ? limit 2", collectRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, paperId)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultCollectModel) FindByUserId(ctx context.Context, userId int64) ([]Collect, error) {
	var resp []Collect
	var query string
	query = fmt.Sprintf("select %s from %s where user_id = %d", collectRows, m.table, userId)
	err := m.conn.QueryRowsCtx(ctx, &resp, query)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultCollectModel) Insert(ctx context.Context, data *Collect) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, collectRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.PaperId)
	return ret, err
}

func (m *defaultCollectModel) Update(ctx context.Context, data *Collect) error {
	query := fmt.Sprintf("update %s set %s where `collect_id` = ?", m.table, collectRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.PaperId, data.CollectId)
	return err
}

func (m *defaultCollectModel) tableName() string {
	return m.table
}
