// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	grievanceFieldNames          = builder.RawFieldNames(&Grievance{})
	grievanceRows                = strings.Join(grievanceFieldNames, ",")
	grievanceRowsExpectAutoSet   = strings.Join(stringx.Remove(grievanceFieldNames, "`grievance_id`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`"), ",")
	grievanceRowsWithPlaceHolder = strings.Join(stringx.Remove(grievanceFieldNames, "`grievance_id`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`"), "=?,") + "=?"

	cacheGrievanceGrievanceIdPrefix = "cache:grievance:grievanceId:"
)

type (
	grievanceModel interface {
		Insert(ctx context.Context, data *Grievance) (sql.Result, error)
		FindOne(ctx context.Context, grievanceId int64) (*Grievance, error)
		Update(ctx context.Context, data *Grievance) error
		Delete(ctx context.Context, grievanceId int64) error
	}

	defaultGrievanceModel struct {
		sqlc.CachedConn
		table string
	}

	Grievance struct {
		GrievanceId int64 `db:"grievance_id"`
		PlaintiffId int64 `db:"plaintiff_id"` // 申诉学者id
		DefendantId int64 `db:"defendant_id"` // 被申诉学者id
		PaperId     int64 `db:"paper_id"`
	}
)

func newGrievanceModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultGrievanceModel {
	return &defaultGrievanceModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`grievance`",
	}
}

func (m *defaultGrievanceModel) Delete(ctx context.Context, grievanceId int64) error {
	grievanceGrievanceIdKey := fmt.Sprintf("%s%v", cacheGrievanceGrievanceIdPrefix, grievanceId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `grievance_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, grievanceId)
	}, grievanceGrievanceIdKey)
	return err
}

func (m *defaultGrievanceModel) FindOne(ctx context.Context, grievanceId int64) (*Grievance, error) {
	grievanceGrievanceIdKey := fmt.Sprintf("%s%v", cacheGrievanceGrievanceIdPrefix, grievanceId)
	var resp Grievance
	err := m.QueryRowCtx(ctx, &resp, grievanceGrievanceIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `grievance_id` = ? limit 1", grievanceRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, grievanceId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGrievanceModel) Insert(ctx context.Context, data *Grievance) (sql.Result, error) {
	grievanceGrievanceIdKey := fmt.Sprintf("%s%v", cacheGrievanceGrievanceIdPrefix, data.GrievanceId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, grievanceRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.PlaintiffId, data.DefendantId, data.PaperId)
	}, grievanceGrievanceIdKey)
	return ret, err
}

func (m *defaultGrievanceModel) Update(ctx context.Context, data *Grievance) error {
	grievanceGrievanceIdKey := fmt.Sprintf("%s%v", cacheGrievanceGrievanceIdPrefix, data.GrievanceId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `grievance_id` = ?", m.table, grievanceRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.PlaintiffId, data.DefendantId, data.PaperId, data.GrievanceId)
	}, grievanceGrievanceIdKey)
	return err
}

func (m *defaultGrievanceModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheGrievanceGrievanceIdPrefix, primary)
}

func (m *defaultGrievanceModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `grievance_id` = ? limit 1", grievanceRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultGrievanceModel) tableName() string {
	return m.table
}
