// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	likeFieldNames          = builder.RawFieldNames(&Like{})
	likeRows                = strings.Join(likeFieldNames, ",")
	likeRowsExpectAutoSet   = strings.Join(stringx.Remove(likeFieldNames, "`like_id`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`"), ",")
	likeRowsWithPlaceHolder = strings.Join(stringx.Remove(likeFieldNames, "`like_id`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`"), "=?,") + "=?"
)

type (
	likeModel interface {
		Insert(ctx context.Context, data *Like) (sql.Result, error)
		FindOne(ctx context.Context, likeId int64) (*Like, error)
		FindLikeId(ctx context.Context, userId int64, commentId int64) (*Like, error)
		Update(ctx context.Context, data *Like) error
		Delete(ctx context.Context, likeId int64) error
	}

	defaultLikeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Like struct {
		LikeId    int64 `db:"like_id"`
		UserId    int64 `db:"user_id"`
		CommentId int64 `db:"comment_id"`
	}
)

func newLikeModel(conn sqlx.SqlConn) *defaultLikeModel {
	return &defaultLikeModel{
		conn:  conn,
		table: "`like`",
	}
}

func (m *defaultLikeModel) Delete(ctx context.Context, likeId int64) error {
	query := fmt.Sprintf("delete from %s where `like_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, likeId)
	return err
}

func (m *defaultLikeModel) FindOne(ctx context.Context, likeId int64) (*Like, error) {
	query := fmt.Sprintf("select %s from %s where `like_id` = ? limit 1", likeRows, m.table)
	var resp Like
	err := m.conn.QueryRowCtx(ctx, &resp, query, likeId)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLikeModel) FindLikeId(ctx context.Context, userId int64, commentId int64) (*Like, error) {
	var resp Like
	var query string
	query = fmt.Sprintf("select %s from %s where user_id = %d and comment_id=%d", likeRows, m.table, userId, commentId)
	err := m.conn.QueryRowCtx(ctx, &resp, query)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLikeModel) Insert(ctx context.Context, data *Like) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, likeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.CommentId)
	return ret, err
}

func (m *defaultLikeModel) Update(ctx context.Context, data *Like) error {
	query := fmt.Sprintf("update %s set %s where `like_id` = ?", m.table, likeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.CommentId, data.LikeId)
	return err
}

func (m *defaultLikeModel) tableName() string {
	return m.table
}
