// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	subscribeFieldNames          = builder.RawFieldNames(&Subscribe{})
	subscribeRows                = strings.Join(subscribeFieldNames, ",")
	subscribeRowsExpectAutoSet   = strings.Join(stringx.Remove(subscribeFieldNames, "`subscribe_id`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`", "`create_time`", "`update_at`"), ",")
	subscribeRowsWithPlaceHolder = strings.Join(stringx.Remove(subscribeFieldNames, "`subscribe_id`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`", "`create_time`", "`update_at`"), "=?,") + "=?"

	cacheSubscribeSubscribeIdPrefix = "cache:subscribe:subscribeId:"
)

type (
	subscribeModel interface {
		Insert(ctx context.Context, data *Subscribe) (sql.Result, error)
		FindOne(ctx context.Context, subscribeId int64) (*Subscribe, error)
		FindSubscribeId(ctx context.Context, userId int64, scholarId int64) (*Subscribe, error)
		Update(ctx context.Context, data *Subscribe) error
		Delete(ctx context.Context, subscribeId int64) error
	}

	defaultSubscribeModel struct {
		sqlc.CachedConn
		table string
	}

	Subscribe struct {
		SubscribeId int64 `db:"subscribe_id"`
		UserId      int64 `db:"user_id"`
		ScholarId   int64 `db:"scholar_id"`
	}
)

func newSubscribeModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultSubscribeModel {
	return &defaultSubscribeModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`subscribe`",
	}
}

func (m *defaultSubscribeModel) Delete(ctx context.Context, subscribeId int64) error {
	subscribeSubscribeIdKey := fmt.Sprintf("%s%v", cacheSubscribeSubscribeIdPrefix, subscribeId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `subscribe_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, subscribeId)
	}, subscribeSubscribeIdKey)
	return err
}

func (m *defaultSubscribeModel) FindOne(ctx context.Context, subscribeId int64) (*Subscribe, error) {
	subscribeSubscribeIdKey := fmt.Sprintf("%s%v", cacheSubscribeSubscribeIdPrefix, subscribeId)
	var resp Subscribe
	err := m.QueryRowCtx(ctx, &resp, subscribeSubscribeIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `subscribe_id` = ? limit 1", subscribeRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, subscribeId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultSubscribeModel) FindSubscribeId(ctx context.Context, userId int64, scholarId int64) (*Subscribe, error) {
	subscribeSubscribeIdKey := fmt.Sprintf("%s%v%v", cacheSubscribeSubscribeIdPrefix, userId, scholarId)
	var resp Subscribe
	err := m.QueryRowCtx(ctx, &resp, subscribeSubscribeIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `scholar_id`=? limit 2", subscribeRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, userId, scholarId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultSubscribeModel) Insert(ctx context.Context, data *Subscribe) (sql.Result, error) {
	subscribeSubscribeIdKey := fmt.Sprintf("%s%v", cacheSubscribeSubscribeIdPrefix, data.SubscribeId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, subscribeRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.ScholarId)
	}, subscribeSubscribeIdKey)
	return ret, err
}

func (m *defaultSubscribeModel) Update(ctx context.Context, data *Subscribe) error {
	subscribeSubscribeIdKey := fmt.Sprintf("%s%v", cacheSubscribeSubscribeIdPrefix, data.SubscribeId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `subscribe_id` = ?", m.table, subscribeRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.ScholarId, data.SubscribeId)
	}, subscribeSubscribeIdKey)
	return err
}

func (m *defaultSubscribeModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheSubscribeSubscribeIdPrefix, primary)
}

func (m *defaultSubscribeModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `subscribe_id` = ? limit 1", subscribeRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSubscribeModel) tableName() string {
	return m.table
}
