// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	applyFieldNames          = builder.RawFieldNames(&Apply{})
	applyRows                = strings.Join(applyFieldNames, ",")
	applyRowsExpectAutoSet   = strings.Join(stringx.Remove(applyFieldNames, "`applyId`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`"), ",")
	applyRowsWithPlaceHolder = strings.Join(stringx.Remove(applyFieldNames, "`applyId`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`"), "=?,") + "=?"

	cacheApplyApplyIdPrefix = "cache:apply:applyId:"
)

type (
	applyModel interface {
		Insert(ctx context.Context, data *Apply) (sql.Result, error)
		FindOne(ctx context.Context, applyId int64) (*Apply, error)
		Update(ctx context.Context, data *Apply) error
		Delete(ctx context.Context, applyId int64) error
	}

	defaultApplyModel struct {
		sqlc.CachedConn
		table string
	}

	Apply struct {
		ApplyId   int64     `db:"applyId"`
		UserId    int64     `db:"userId"`    // 用户id
		ScholarId int64     `db:"scholarId"` // 学者id
		Status    int64     `db:"status"`    // 处理状态
		ApplyType int64     `db:"applyType"` // 认证类型
		Email     string    `db:"email"`     // 认证邮箱
		Url       string    `db:"url"`       // 认证证件
		ApplyTime time.Time `db:"applyTime"`
	}
)

func newApplyModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultApplyModel {
	return &defaultApplyModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`apply`",
	}
}

func (m *defaultApplyModel) Delete(ctx context.Context, applyId int64) error {
	applyApplyIdKey := fmt.Sprintf("%s%v", cacheApplyApplyIdPrefix, applyId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `applyId` = ?", m.table)
		return conn.ExecCtx(ctx, query, applyId)
	}, applyApplyIdKey)
	return err
}

func (m *defaultApplyModel) FindOne(ctx context.Context, applyId int64) (*Apply, error) {
	applyApplyIdKey := fmt.Sprintf("%s%v", cacheApplyApplyIdPrefix, applyId)
	var resp Apply
	err := m.QueryRowCtx(ctx, &resp, applyApplyIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `applyId` = ? limit 1", applyRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, applyId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultApplyModel) Insert(ctx context.Context, data *Apply) (sql.Result, error) {
	applyApplyIdKey := fmt.Sprintf("%s%v", cacheApplyApplyIdPrefix, data.ApplyId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, applyRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.ScholarId, data.Status, data.ApplyType, data.Email, data.Url, data.ApplyTime)
	}, applyApplyIdKey)
	return ret, err
}

func (m *defaultApplyModel) Update(ctx context.Context, data *Apply) error {
	applyApplyIdKey := fmt.Sprintf("%s%v", cacheApplyApplyIdPrefix, data.ApplyId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `applyId` = ?", m.table, applyRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.ScholarId, data.Status, data.ApplyType, data.Email, data.Url, data.ApplyTime, data.ApplyId)
	}, applyApplyIdKey)
	return err
}

func (m *defaultApplyModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheApplyApplyIdPrefix, primary)
}

func (m *defaultApplyModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `applyId` = ? limit 1", applyRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultApplyModel) tableName() string {
	return m.table
}
