// Code generated by goctl. DO NOT EDIT.
package types

type ApplyInfo struct {
	ApplyId     int64  `json:"apply_id"`
	ScholarName string `json:"scholar_name"`
	Institution string `json:"institution"`
	ApplyType   int64  `json:"apply_type"`
	Email       string `json:"email"`
	URL         string `json:"url"`
}

type GetApplyResponse struct {
	ApplyList []ApplyInfo `json:"records"`
}

type DealApplyRequest struct {
	ApplyId int64 `json:"apply_id"`
	IsAgree bool  `json:"is_agree"`
}

type EmailIdentifyRequest struct {
	Email     string `json:"email"`
	ScholarId int64  `json:"scholar_id"`
}
