// Code generated by goctl. DO NOT EDIT.
// Source: paper.proto

package streamgreeter

import (
	"context"

	"soft2_backend/service/paper/rpc/types/paper"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CheckScholarReq    = paper.CheckScholarReq
	CreateScholarReply = paper.CreateScholarReply
	MovePaperReply     = paper.MovePaperReply
	MovePaperReq       = paper.MovePaperReq

	StreamGreeter interface {
		CheckScholar(ctx context.Context, in *CheckScholarReq, opts ...grpc.CallOption) (*CreateScholarReply, error)
		MovePaper(ctx context.Context, in *MovePaperReq, opts ...grpc.CallOption) (*MovePaperReply, error)
	}

	defaultStreamGreeter struct {
		cli zrpc.Client
	}
)

func NewStreamGreeter(cli zrpc.Client) StreamGreeter {
	return &defaultStreamGreeter{
		cli: cli,
	}
}

func (m *defaultStreamGreeter) CheckScholar(ctx context.Context, in *CheckScholarReq, opts ...grpc.CallOption) (*CreateScholarReply, error) {
	client := paper.NewStreamGreeterClient(m.cli.Conn())
	return client.CheckScholar(ctx, in, opts...)
}

func (m *defaultStreamGreeter) MovePaper(ctx context.Context, in *MovePaperReq, opts ...grpc.CallOption) (*MovePaperReply, error) {
	client := paper.NewStreamGreeterClient(m.cli.Conn())
	return client.MovePaper(ctx, in, opts...)
}
