// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	helpFileFieldNames          = builder.RawFieldNames(&HelpFile{})
	helpFileRows                = strings.Join(helpFileFieldNames, ",")
	helpFileRowsExpectAutoSet   = strings.Join(stringx.Remove(helpFileFieldNames, "`updated_at`", "`update_time`", "`create_at`", "`created_at`", "`create_time`", "`update_at`"), ",")
	helpFileRowsWithPlaceHolder = strings.Join(stringx.Remove(helpFileFieldNames, "`help_id`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`", "`create_time`", "`update_at`"), "=?,") + "=?"
)

type (
	helpFileModel interface {
		Insert(ctx context.Context, data *HelpFile) (sql.Result, error)
		FindOne(ctx context.Context, helpId int64) (*HelpFile, error)
		Update(ctx context.Context, data *HelpFile) error
		Delete(ctx context.Context, helpId int64) error
	}

	defaultHelpFileModel struct {
		conn  sqlx.SqlConn
		table string
	}

	HelpFile struct {
		HelpId   int64  `db:"help_id"`
		FileName string `db:"file_name"`
	}
)

func newHelpFileModel(conn sqlx.SqlConn) *defaultHelpFileModel {
	return &defaultHelpFileModel{
		conn:  conn,
		table: "`help_file`",
	}
}

func (m *defaultHelpFileModel) Delete(ctx context.Context, helpId int64) error {
	query := fmt.Sprintf("delete from %s where `help_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, helpId)
	return err
}

func (m *defaultHelpFileModel) FindOne(ctx context.Context, helpId int64) (*HelpFile, error) {
	query := fmt.Sprintf("select %s from %s where `help_id` = ? limit 1", helpFileRows, m.table)
	var resp HelpFile
	err := m.conn.QueryRowCtx(ctx, &resp, query, helpId)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultHelpFileModel) Insert(ctx context.Context, data *HelpFile) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, helpFileRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.HelpId, data.FileName)
	return ret, err
}

func (m *defaultHelpFileModel) Update(ctx context.Context, data *HelpFile) error {
	query := fmt.Sprintf("update %s set %s where `help_id` = ?", m.table, helpFileRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.FileName, data.HelpId)
	return err
}

func (m *defaultHelpFileModel) tableName() string {
	return m.table
}
