// Code generated by goctl. DO NOT EDIT.
package types

type MessageInfo struct {
	MessageId   int64  `json:"id"`
	MessageType int64  `json:"type"`
	UId         int64  `json:"uid,optional"`
	GId         int64  `json:"gid,optional"`
	PId         string `json:"pid,optional"`
	RId         int64  `json:"rid,optional"`
	Result      int64  `json:"result,optional"`
	Content     string `json:"content"`
	Read        bool   `json:"read"`
	MessageTime string `json:"msg_time"`
}

type GetMessageRequest struct {
	Start int64 `json:"start,optional"`
	End   int64 `json:"end,optional"`
}

type GetMessageResponse struct {
	Count       int64         `json:"msg_num"`
	MessageList []MessageInfo `json:"messages"`
}

type ReadMessageRequest struct {
	MessageId int64 `json:"id"`
}

type DeleteMessageRequest struct {
	MessageId int64 `json:"id"`
}
