// Code generated by goctl. DO NOT EDIT!
// Source: message.proto

package server

import (
	"context"

	"go-zero-share/message/rpc/internal/logic"
	"go-zero-share/message/rpc/internal/svc"
	"go-zero-share/message/rpc/types/message"
)

type MessageServer struct {
	svcCtx *svc.ServiceContext
	message.UnimplementedMessageServer
}

func NewMessageServer(svcCtx *svc.ServiceContext) *MessageServer {
	return &MessageServer{
		svcCtx: svcCtx,
	}
}

func (s *MessageServer) CreateMessage(ctx context.Context, in *message.CreateMessageReq) (*message.CreateMessageReply, error) {
	l := logic.NewCreateMessageLogic(ctx, s.svcCtx)
	return l.CreateMessage(in)
}
