// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	LoginId  string `json:"login_id"`
	PassWord string `json:"password"`
}

type LoginResponse struct {
	Code     int64  `json:"code"` //0登录成功 1用户名不存在 2 密码错误
	UserId   int64  `json:"user_id"`
	Token    string `json:"token"`
	NickName string `json:"nick_name"`
}

type RegisterRequest struct {
	LoginId  string `json:"login_id"`
	Nickname string `json:"nickname"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type RegisterResponse struct {
	Code     int64  `json:"code"`
	UserId   int64  `json:"user_id"`
	Token    string `json:"token"`
	NickName string `json:"nick_name"`
}

type UserInfoRequest struct {
}

type UserInfoResponse struct {
	Nickname   string `json:"nickname"`
	Email      string `json:"email"`
	Requests   int64  `json:"n_request"`  //求助次数
	Helps      int64  `json:"n_help"`     //应助次数
	Follows    int64  `json:"follows"`    //关注学者量
	Complaints int64  `json:"complaints"` //投诉次数
	Wealth     int64  `json:"wealth"`     //财富值
}

type CollectPaperRequest struct {
	PaperId int64 `json:"paper_id"`
}

type CollectPaperResponse struct {
	Code int64 `json:"code"` //0收藏成功 1已收藏 2尚未登录
}

type CancelCollectPaperRequest struct {
	PaperId int64 `json:"paper_id"`
}

type CancelCollectPaperResponse struct {
	Code int64 `json:"code"` //0取消成功 1尚未登录
}

type CommentPaperRequest struct {
	PaperId int64  `json:"paper_id"`
	Content string `json:"content"`
}

type CommentPaperResponse struct {
	Code int64 `json:"code"` //0表示成功 1尚未登录 2检测到不合适字段
}

type DeleteCommentRequest struct {
	CommentId int64 `json:"comment_id"`
}

type DeleteCommentResponse struct {
	Code int64 `json:"code"` //0成功 1尚未登录
}

type LikeCommentRequest struct {
	CommentId int64 `json:"comment_id"`
}

type LikeCommentResponse struct {
	Code int64 `json:"code"` //0成功 1尚未登录
}

type CancelLikeRequest struct {
	CommentId int64 `json:"comment_id"`
}

type CancelLikeResponse struct {
	Code int64 `json:"code"`
}
