name: Java CI with Maven

on:
  push:
    # 分支
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Running go
    steps:
      - name: 在服务器上执行 sudo go run
        if: always()
        uses: fifsky/ssh-action@master
        with:
          command: | # down命令必须在pull前进行
            cd soft2/soft2_backend/  
            sudo mkdir cache/message/api
            sudo mkdir cache/message/rpc
            sudo mkdir cache/file/api
            sudo mkdir cache/file/rpc
            sudo mkdir cache/paper/api
            sudo mkdir cache/paper/rpc
            sudo mkdir cache/user/api
            sudo mkdir cache/user/rpc
            sudo mkdir cache/apply/api
            sudo mkdir cache/apply/rpc
            sudo mkdir cache/help/api
            sudo mkdir cache/help/rpc
            sudo docker compose down
            sudo git fetch --all
            sudo git checkout main
            sudo git pull
            sudo docker compose build -q
            sudo docker compose up -d
          host: ${{ secrets.HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASSWORD }}
          args: "-tt"